services:
  shapeblock:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.sb

  redis:
    image: "redis:alpine"

  db:
    image: postgres:16
    volumes:
      - shapeblock_db_data:/var/lib/postgresql/data
    env_file:
      - ./.env.sb

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8026:8025"

volumes:
  shapeblock_db_data: {}
