defaultImage: ghcr.io/shapeblock/sb/backend
defaultImageTag: 2024-04-20.3
defaultImagePullPolicy: Always
deployments:
  django:
    initContainers:
    - name: migrate
      command: ['python', 'manage.py', 'migrate']
      envConfigmaps:
      - envs
      envSecrets:
      - secret-envs
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: 5m
          memory: 128M

    containers:
    - envConfigmaps:
      - envs
      envSecrets:
      - secret-envs
      name: django
      command: ['uvicorn', '--host', '0.0.0.0', '--port', '8000', '--workers', '1', 'shapeblock.asgi:application']
      ports:
      - containerPort: 8000
        name: app
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 5m
          memory: 128M
    podLabels:
      app: shapeblock
      release: backend
    replicas: 1
enabled: true
envs:
  DEBUG: "False"
  DATABASE_URL: postgres://shapeblock:xyTYDRE20blju6Qrywidumlt@database-postgresql/shapeblock
  POSTGRES_DB: shapeblock
  POSTGRES_USER: shapeblock
  POSTGRES_PASSWORD: xyTYDRE20blju6Qrywidumlt
  DATABASE_HOST: database-postgresql
  REDIS_HOST: redis-master
  CLUSTER_DOMAIN: "example.com"
  ALLOWED_HOSTS: "*"

generic:
  extraImagePullSecrets:
  - name: registry-creds
  labels:
    app: shapeblock
    release: backend
  usePredefinedAffinity: false

releasePrefix: production
secretEnvs:
  SECRET_KEY: "YYY"
  GH_TOKEN: "zzz"
  FERNET_KEYS: "xxx==,yyy=="

services:
  django:
    extraSelectorLabels:
      app: shapeblock
      release: backend
    ports:
    - port: 8000
    type: ClusterIP

ingresses:
  api.shapeblock.com:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    certManager:
      originalIssuerName: letsencrypt-prod
      issuerType: cluster-issuer
    hosts:
    - paths:
      - serviceName: django
        servicePort: 8000
    ingressClassName: nginx
    name: backend
