# Generated by Django 5.0.6 on 2024-08-21 05:22

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_token',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=200, null=True),
        ),
    ]
