# Generated by Django 5.0.6 on 2024-08-21 05:22

import django.core.validators
import fernet_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$', 'Only alphanumeric characters and - are allowed.')])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('building', 'Building'), ('ready', 'Ready'), ('deleted', 'Deleted')], default='created', max_length=10)),
                ('stack', models.CharField(choices=[('php', 'PHP'), ('java', 'Java'), ('python', 'Python'), ('node', 'Node.js'), ('ruby', 'Ruby'), ('go', 'Golang'), ('nginx', 'Nginx')], max_length=20)),
                ('repo', models.CharField(max_length=256)),
                ('ref', models.CharField(default='main', max_length=256)),
                ('sub_path', models.CharField(blank=True, max_length=256, null=True)),
                ('sb_yml', models.JSONField(blank=True)),
                ('key_config', models.JSONField(blank=True, null=True)),
                ('autodeploy', models.BooleanField(default=False)),
                ('webhook_id', models.BigIntegerField(null=True)),
                ('has_liveness_probe', models.BooleanField(default=True)),
                ('replicas', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]([_A-Za-z0-9]*[A-Za-z0-9])?$', 'Only alphanumeric characters and _ are allowed.')])),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$', 'Please give a valid domain name.')])),
            ],
        ),
        migrations.CreateModel(
            name='EnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]([_A-Za-z0-9]*[A-Za-z0-9])?$', 'Only alphanumeric characters and _ are allowed.')])),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InitProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$', 'Only alphanumeric characters and - are allowed.')])),
                ('memory', models.CharField(default='512Mi', max_length=5)),
                ('cpu', models.CharField(default='500m', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]([_A-Za-z0-9]*[A-Za-z0-9])?$', 'Only alphanumeric characters and _ are allowed.')])),
                ('value', fernet_fields.fields.EncryptedCharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$', 'Only alphanumeric characters and - are allowed.')])),
                ('mount_path', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(message='Path must start with /workspace', regex='^/workspace/.+')])),
                ('size', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$', 'Only alphanumeric characters and - are allowed.')])),
                ('memory', models.CharField(default='1Gi', max_length=5)),
                ('cpu', models.CharField(default='1000m', max_length=5)),
            ],
        ),
    ]
