# Generated by Django 5.0.6 on 2024-08-21 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        ('projects', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='projects.project'),
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildvar',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_vars', to='apps.app'),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='apps.app'),
        ),
        migrations.AddField(
            model_name='envvar',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_vars', to='apps.app'),
        ),
        migrations.AddField(
            model_name='envvar',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='initprocess',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_processes', to='apps.app'),
        ),
        migrations.AddField(
            model_name='secret',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='apps.app'),
        ),
        migrations.AddField(
            model_name='volume',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='apps.app'),
        ),
        migrations.AddField(
            model_name='workerprocess',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='apps.app'),
        ),
        migrations.AlterUniqueTogether(
            name='buildvar',
            unique_together={('key', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='customdomain',
            unique_together={('domain', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='envvar',
            unique_together={('key', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='initprocess',
            unique_together={('key', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('key', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('name', 'mount_path', 'size', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='workerprocess',
            unique_together={('key', 'app')},
        ),
    ]
