# Generated by Django 5.0.6 on 2024-08-04 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envvar',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='initprocess',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.app'),
        ),
        migrations.AddField(
            model_name='secret',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='apps.app'),
        ),
        migrations.AddField(
            model_name='volume',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='apps.app'),
        ),
        migrations.AddField(
            model_name='workerprocess',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.app'),
        ),
        migrations.AlterUniqueTogether(
            name='buildvar',
            unique_together={('key', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='customdomain',
            unique_together={('domain', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='envvar',
            unique_together={('key', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='initprocess',
            unique_together={('key', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('key', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('name', 'mount_path', 'size', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='workerprocess',
            unique_together={('key', 'app')},
        ),
    ]
