# Generated by Django 5.0.6 on 2024-08-20 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_initprocess_app_alter_workerprocess_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='replicas',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
