apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    shapeblock.com/service-uuid: {{ service_uuid }}
spec:
  chart:
    spec:
      chart: postgresql
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux
      version: 13.2.25
  install:
    disableWait: false
    disableWaitForJobs: false
  interval: 5m
  values:
    auth:
      database: shapeblock
      username: shapeblock
      password: shapeblock
      postgresPassword: shapeblock
    architecture: standalone
    primary:
      persistence:
        size: 2Gi
